name: fortitudo.tech-examples
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - seaborn
  - pandas=1.5
  - cvxopt=1.3
  - libblas=*=*mkl
  - pip
  - pip:
      - fortitudo.tech
      - pyportfolioopt
      - yfinance
